name:                pagerduty-hs
version:             0.1.0.1
github:              "dustin/pagerduty-hs"
license:             BSD3
author:              "Dustin Sallings"
maintainer:          "dustin@spy.net"
copyright:           "Copyright © 2021 Dustin Sallings"
synopsis:            An interface to the PagerDuty API.
category:            API

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dustin/pagerduty-hs#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- text
- wreq
- aeson
- exceptions

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - NamedFieldPuns

tests:
  pagerduty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pagerduty-hs
    - HUnit
    - tasty
    - tasty-hunit
    - tasty-quickcheck
