name: "Nix Build"
on:
  push:
    branches:
      - main
  schedule:
  - cron: "3 11 13,27 * *"
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v16
      with:
        name: dustin
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A pagerduty-hs.components.library
